-- MySQL Script generated by MySQL Workbench
-- Wed Apr  9 16:57:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sae_economy_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sae_economy_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sae_economy_db` DEFAULT CHARACTER SET utf8 ;
USE `sae_economy_db` ;

-- -----------------------------------------------------
-- Table `sae_economy_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sae_economy_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(64) NOT NULL,
  `lastname` VARCHAR(64) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `sae_economy_db`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sae_economy_db`.`chat` (
  `chat_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(64) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`chat_id`),
  INDEX `fk_chat_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_chat_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `sae_economy_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sae_economy_db`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sae_economy_db`.`message` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `context` VARCHAR(2000) NULL,
  `content` VARCHAR(2000) NOT NULL,
  `is_user` TINYINT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `chat_id` INT NOT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `fk_message_chat1_idx` (`chat_id` ASC),
  CONSTRAINT `fk_message_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `sae_economy_db`.`chat` (`chat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
